spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emps?serverTimezone=UTC
    password: 123456
    username: root
  jpa:
#    hibernate:
#      ddl-auto: update
    #控制台显示出执行的sql
    show-sql: true